repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff